title: "Klaxon Cloud: Site Monitor and Alerts"
description: >-
  Klaxon enables reporters and editors to monitor scores of sites and files on the web for newsworthy changes. 
  Get email notifications when something changes. Provide a CSS selector to only monitor 
  portions of a page you are interested in. You may supply * to monitor the entire page, but you may receive alerts for trivial changes.
  Email alerts are sent to the primary email address on your DocumentCloud account. 
  To get started, visit [https://www.klaxoncloud.org/](https://www.klaxoncloud.org/) to download the Klaxon browser extension. 
instructions: ""
type: object
properties:
  site:
    title: Site
    type: string
    format: uri
  selector:
    title: Selector
    type: string
    description: CSS Selector on the page you would like to monitor.
  filter_selector:
    title: Filter
    type: string
    description: "Optional HTML tag that you want to filter out from being compared. Ex: Type <code>a</code> for <code>&lt;a&gt;</code> tags"
  title:
    title: Title
    type: string
    description: "Optional descriptive name for this URL"
  slack_webhook:
    title: Slack Webhook
    type: string
    format: uri
    description: Enter a Slack webhook to enable Slack notifications
  discord_webhook:
    title: Discord Webhook
    type: string
    format: uri
    description: Enter a Discord webhook to enable Discord notifications
required:
  - site
  - selector
categories:
  - monitor
custom_disabled_email_footer: "   "
eventOptions:
  name: site
  events:
    - hourly
    - daily
    - weekly


